# Default values for base-apps-web.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: iaguilera640/gitops-lab
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.1"


podAnnotations: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: "true"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/tls-acme: "false"
  hosts:
    - host: appweb.local
      paths:
        - path: /
          pathType: Prefix
  tls: false
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

